### ISSUE TITLE
generic deriving forces importing `I(I)`.

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch-plutus#210]
```haskell
import Generics.SOP (Generic, I(I))
```

The above is required to fix,

```
    • Couldn't match representation of type: sop-core-0.5.0.2:Data.SOP.BasicFunctors.I
                                               (Term s SwapAction)
                               with that of: Term s SwapAction
        arising from the 'deriving' clause of a data type declaration
      The data constructor ‘sop-core-0.5.0.2:Data.SOP.BasicFunctors.I’
        of newtype ‘sop-core-0.5.0.2:Data.SOP.BasicFunctors.I’
        is not in scope
    • When deriving the instance for (PlutusType Action)
   |
39 |   deriving anyclass (Generic, PlutusType)
```

But users shouldn't have to import `I(I)` when it is not used directly in the module.

**Comment by TotallyNotChase** [comment]
I need to put this in the guide.

**Comment by MangoIV** [comment]
I don't know if it's totally obvious but I think I found the reason for this: 
Say you have a datatype
`T` with a constructor `MkT` you can coerce to the representation type by using `coerce`, however, this is forbidden in GHC if the constructor of `T` is not in scope for the reason of hiding abstractions. 
This is a thing because the current opinion of the `GHC`-devs is, that developers might not know how to do `role` annotations (in this case you would want `nominal` afaik) and hence this adds safety. 
I think the best way around this is not to use anything `coerce` in the `default` implementation.
