### ISSUE TITLE
Plutarch 1.2

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#315]
Minor update because of #314 , new Plutus breaks a lot of things. How should we do this?

@srid 
@TotallyNotChase 
@t1lde 
@blamario 
@emiflake 
(sorry for the ones whom I forgot)

**Comment by srid** [comment]
> new Plutus breaks a lot of things

Are these visible to users of Plutarch (aside from differing benchmarks)?

**Comment by L-as** [comment]
Yes, e.g. PSignature was removed as Signature was removed upstream.

**Comment by TotallyNotChase** [comment]
Well, we should perhaps switch to staging workflow if we have breaking changes right now but still have issues to fix. If everything can be fixed with one PR, then I'm all for merging to master, drafting up the changelog and just releasing.

Can we please have a list of the issues that need tackling for this release?

**Comment by L-as** [comment]
I agree with that. Let's switch to that.

**Comment by L-as** [comment]
We need to fix #331
