### ISSUE TITLE
Remove PBuiltinMap

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#513]

**Comment by MangoIV** [comment]
I would like to understand your reasoning behind this; PBuiltinMap is just a type alias for list of pairs. Why would we remove this? Should people using V1 api really be writing PBulitinList (PBulitinPair (PasData a) (PAsData b)) instead of PBuiltinMap? 
Maybe we want to rename it to something else? Like `PListOfPairs`?

**Comment by L-as** [comment]
When would a user ever write it out?

**Comment by MangoIV** [comment]
whenever they need the equivalent of a PBulitinMap?

**Comment by L-as** [comment]
...and when do they need that?
