### ISSUE TITLE
Remove POrd for PValue

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch-plutus#526]
It doesn't form a total order and can break e.g. `Data.Map` if you have a map of terms of values.
It can possibly also break `PMap`.
cc @TotallyNotChase

**Comment by TotallyNotChase** [comment]
This makes sense to me - that's why I questioned whether the `POrd` instance should be added! I'll quickly remove that now then

**Comment by TotallyNotChase** [comment]
One small issue I can think of however: how do you handle the guarantees? Ideally you want to allow both `'Positive` and `'NonZero` at the very least - but you would need a typeclass to allow both with the same `pleq` for example. Otherwise, they'd need to be separate functions.

Though `pleq` (and indeed `pgeq`) could be allowed for any `AmountGuarantees` if I'm not mistaken. It's `plt` and `pgt` that need a separate check to ensure they aren't equal, in the case where `AmountGuarantees` is `NoGuarantees`.

**Comment by blamario** [comment]
The optimal implementations of `pleq` for different `AmountGuarantees` are all going to be different, with the `Positive` case the simplest one. If you're going to add a new typeclass, call it `PPartialOrd` I guess, and place it next to `POrd` since it would become its superclass. The only other instance I can think of is

    instance (PPartialOrd a, PIsData k, PIsData a) => PPartialOrd (PMap k a)

**Comment by TotallyNotChase** [comment]
@blamario Would `NonZero` and `Positive` have different implementations? I thought they'd both have the same thing. Could you explain what special properties `Positive` can leverage compared to `NonZero`?

**Comment by blamario** [comment]
In case of `Positive` you can just check if for every `(key, value1) <- map1` there is a corresponding `(key, value2)` in the other map and `value1 <- value2`. In case of `NonZero` you also have to check if the second map contains a negative value not present in the first one.

**Comment by TotallyNotChase** [comment]
I feel like both of these cases would be optimally covered by [this `pcheckBinRel` impl](https://github.com/Plutonomicon/plutarch-plutus/blob/c25c5a7cad5591156e2ec132677b1f37990bd921/Plutarch/Api/V1/AssocMap.hs#L478) - at least, I can't quite see what would be wrong. Please do enlighten me on what I'm missing here.

**Comment by blamario** [comment]
That implementation may be optimal for the `NonZero` case, but for `Positive` values the `f # v1 # z` and `f # z # v2` will always be `True` and `False` respectively.

**Comment by L-as** [comment]
i don't think this optimisation is worth pursuing now.

**Comment by TotallyNotChase** [comment]
@blamario But whether or not `f # v1 # z` is always `True` (or vice versa) depends entirely on `f` right? It would be always `True` for "greater than" but not "less than", for example. I don't really see this as an optimization if the only way to implement this is to duplicate a huge AST or to add even more parameterization. I _think_ it's the most optimal the way it is.

In any case, @L-as what do you suggest about the polymorphism business? We want the same `pleq` and `ple` (ideally) for `Positive` and `NonZero`, but not `NoGuarantees`. Is this a cue for yet another typeclass?

**Comment by L-as** [comment]
PPartialOrd? @TotallyNotChase

**Comment by blamario** [comment]
@TotallyNotChase 
> But whether or not f # v1 # z is always True (or vice versa) depends entirely on f right?

Yes. Whether the splitting of the function would be an optimization or not depends on whether a script uses both variants of the comparison functions, and then if it does also on how many times the `Positive` case is used.
